export { HASH_ID_PATTERN, deterministicId } from "./ids.js";
export {
  fetchDocument,
  importDirectory,
  listDeletionReceipts,
  listSources,
  openVault,
  prepareSourcePurge,
  purgeDocument,
  purgeSource,
  searchVault,
  verifyDeletionReceipt,
} from "./vault.js";
export type {
  DeletionReceipt,
  DeletionReceiptVerification,
  FetchDocumentInput,
  FetchedChunk,
  ImportDirectoryOptions,
  ImportDirectoryResult,
  ImportPhase,
  ImportProgress,
  ImportedDocument,
  ImportIssue,
  ImportIssueCode,
  PrepareSourcePurgeResult,
  PurgeSourceInput,
  PurgeSourceResult,
  SearchVaultInput,
  SourcePurgePreview,
  Vault,
  VaultFetchResult,
  VaultResult,
  VaultSearchResult,
  VaultSource,
} from "./types.js";
